### ISSUE TITLE
Display splash screen when device being flashed has screen

### ISSUE THREAD

**Issue by jhermsmeier** [balena-io-modules/node-raspberrypi-usbboot#12]
Feature request from https://github.com/resin-io/etcher/issues/2419#issuecomment-406617825

TL;DR: In order to not confuse (non-technical) users, it might make sense to suppress console output to screens (if attached) while in usbboot mode, and either display nothing, or display a splash screen

**Comment by lurch** [comment]
AFAIK this is _actually_ an issue for https://github.com/resin-os/amber-etcher-kernel ? But of course things might have changed around since I last looked at them... :-)
Ping @agherzan
